[package]
name = "aoctool"
version = "0.1.0"
authors = ["Peter Goodspeed-Niklaus <peter.r.goodspeedniklaus@gmail.com>"]
edition = "2018"

[dependencies]
aoclib = { git = "https://github.com/coriolinus/aocutil.git" }
chrono = "0.4.22"
color-eyre = "0.6.2"
path-absolutize = "3.0.13"
pathdiff = "0.2.1"
reqwest = { version = "0.11.12", features = [ "blocking", "gzip" ] }
serde = { version = "1.0.145", features = [ "derive" ] }
structopt = "0.3.26"
thiserror = "1.0.37"
tinytemplate = "1.2.1"
toml = "0.5.9"
toml_edit = "0.14.4"

[[bin]]
name = "aoc"
path = "src/main.rs"
